# Generated by Django 4.1 on 2022-11-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_coeppost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coeppost',
            old_name='author',
            new_name='coepauthor',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='content',
            new_name='coepcontent',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='slug',
            new_name='coepslug',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='sno',
            new_name='coepsno',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='timeStamp',
            new_name='coeptimeStamp',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='title',
            new_name='coeptitle',
        ),
        migrations.RenameField(
            model_name='coeppost',
            old_name='views',
            new_name='coepviews',
        ),
    ]
